name: Readora CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Stage
        run: echo "Building Readora"

      - name: Test Stage
        run: echo "Testing Readora"

      - name: Deploy Stage
        run: echo "Deploying Readora"

      - name: Pipeline Success
        run: echo "Readora Pipeline Successful"
